# Generated by Django 4.1.5 on 2023-02-10 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventScheduler',
        ),
    ]
