# Generated by Django 4.1.5 on 2023-02-10 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin', '0002_delete_eventscheduler'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventScheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=20)),
                ('event_data_time', models.CharField(max_length=20)),
            ],
        ),
    ]
